version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: vercel_clone_redis
    ports:
      - "6600:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api-server:
    build:
      context: ./api-server
      target: builder # Use builder stage for dev to get ts-node-dev
    container_name: vercel_clone_api
    command: sh -c "npx prisma generate && npm run dev" 
    ports:
      - "8800:8800"
    volumes:
      - ./api-server:/usr/src/app
      - /usr/src/app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock # Mount Docker socket for raw Daemon access
    environment:
      - DATABASE_URL=${DATABASE_URL} # REPLACE THIS URL WITH YOUR ACTUAL NEON URL
      - REDIS_URL=redis://redis:6379
      - ACCESSKEY=local_dummy
      - SECRETKEY=local_dummy
      - DOCKER_NETWORK=vercelserver_default
    depends_on:
      redis:
        condition: service_healthy

  s3-reverse-proxy:
    build:
      context: ./s3-reverse-proxy
      target: builder
    container_name: vercel_clone_proxy
    command: npm run dev
    ports:
      - "8000:8000"
    volumes:
      - ./s3-reverse-proxy:/usr/src/app
      - /usr/src/app/node_modules

volumes:
  redisdata:
